In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('geoparsing-results-EUPEG.xlsx')
df.head()

  dataset    geoparser  precision  recall  f-score  accuracy
0     LGL    Edinburgh      0.723   0.383    0.501     0.383
1     LGL  TopoCluster      0.763   0.577    0.657     0.577
2     LGL       CLAVIN      0.808   0.444    0.573     0.444
3     LGL     CamCoder      0.811   0.548    0.654     0.548
4     LGL  StanfordNER      0.744   0.622    0.677     0.622
5     LGL     SpaCyNER      0.493   0.371    0.423     0.371
6     LGL      DBpedia      0.813   0.635    0.713     0.635
7     LGL   DM_NLP+Pop      0.730   0.630    0.677       NaN
8     LGL  UniMelb+Pop      0.694   0.653    0.673       NaN

### F score rank

In [3]:
fscore_df = df.pivot(index='geoparser', columns='dataset', values='f-score')
rank_df = fscore_df.rank(method='min', ascending=False).astype(int)
rank_df['total'] = rank_df.sum(axis=1)
rank_df.sort_values('total')

dataset      GeoCorpora  GeoVirus  GeoWebNews  LGL  TR-News  total
geoparser
StanfordNER           3         2           1    2        1      9
DM_NLP+Pop            1         1           3    2        6     13
UniMelb+Pop           2         3           2    4        5     16
CamCoder              4         4           4    6        3     21
TopoCluster           5         5           5    5        2     22
DBpedia               6         7           7    1        4     25
CLAVIN                9         6           8    7        7     37
Edinburgh             7         8           6    8        8     37
SpaCyNER              8         9           9    9        9     44

In [5]:
fscore_var = fscore_df.var(axis=1).sort_values(ascending=False)
fscore_mean = fscore_df.mean(axis=1).sort_values(ascending=False)

print('variance')
print(fscore_var)
print()
print('mean')
print(fscore_mean)

variance
geoparser
StanfordNER    0.010605
DM_NLP+Pop     0.009951
CLAVIN         0.009747
UniMelb+Pop    0.008223
TopoCluster    0.008168
CamCoder       0.008129
Edinburgh      0.004590
SpaCyNER       0.002687
DBpedia        0.001904
dtype: float64

mean
geoparser
StanfordNER    0.7596
UniMelb+Pop    0.7526
DM_NLP+Pop     0.7502
TopoCluster    0.7208
CamCoder       0.7208
DBpedia        0.6808
Edinburgh      0.6138
CLAVIN         0.6034
SpaCyNER       0.4888
dtype: float64

In [6]:
precision_df = df.pivot(index='geoparser', columns='dataset', values='precision')
precision_var = precision_df.var(axis=1).sort_values(ascending=False)
precision_mean = precision_df.mean(axis=1).sort_values(ascending=False)

print('variance')
print(precision_var)
print()
print('mean')
print(precision_mean)

variance
geoparser
SpaCyNER       0.009563
DM_NLP+Pop     0.007180
UniMelb+Pop    0.005525
StanfordNER    0.005147
Edinburgh      0.004636
TopoCluster    0.002636
CamCoder       0.002252
CLAVIN         0.002055
DBpedia        0.001013
dtype: float64

mean
geoparser
CamCoder       0.8894
CLAVIN         0.8890
StanfordNER    0.8690
TopoCluster    0.8486
DBpedia        0.8356
DM_NLP+Pop     0.8298
UniMelb+Pop    0.8242
Edinburgh      0.7886
SpaCyNER       0.6278
dtype: float64

In [7]:
recall_df = df.pivot(index='geoparser', columns='dataset', values='recall')
recall_var = recall_df.var(axis=1).sort_values(ascending=False)
recall_mean = recall_df.mean(axis=1).sort_values(ascending=False)

print('variance')
print(recall_var)
print()
print('mean')
print(recall_mean)

variance
geoparser
StanfordNER    0.020344
UniMelb+Pop    0.017713
DM_NLP+Pop     0.016595
TopoCluster    0.015925
CamCoder       0.013811
CLAVIN         0.013010
Edinburgh      0.004994
DBpedia        0.004552
SpaCyNER       0.001439
dtype: float64

mean
geoparser
UniMelb+Pop    0.6998
DM_NLP+Pop     0.6890
StanfordNER    0.6834
TopoCluster    0.6338
CamCoder       0.6106
DBpedia        0.5784
Edinburgh      0.5046
CLAVIN         0.4642
SpaCyNER       0.4022
dtype: float64